parameters:
    pim_datagrid.product.attribute_type.pim_extended_attribute_type_range:
        column:
            type:          product_value_range
            selector:      product_value_range
            frontend_type: html
        filter:
            type:          product_value_range
            ftype:         range
            options:
                field_options:
                    attr:
                        empty_choice: true
        sorter:            ~

    pim_datagrid.product.attribute_type.pim_extended_attribute_type_text_collection:
        column:
            type:          product_value_text_collection
            selector:      product_value_base
            frontend_type: html
        filter:
            type:          product_value_string
            ftype:         string
            options:
                field_options:
                    attr:
                        empty_choice: true
        sorter:            ~

