parameters:
    pim_extended_attribute_type.datagrid.extension.formatter.property.product_value.string_collection.class: Pim\Bundle\ExtendedAttributeTypeBundle\DataGrid\Extension\Formatter\Property\ProductValue\StringCollectionProperty

services:
    pim_extended_attribute_type.datagrid.extension.formatter.property.product_value.string_collection:
        class: '%pim_extended_attribute_type.datagrid.extension.formatter.property.product_value.string_collection.class%'
        arguments:
            - '@twig'
            - '@translator'
            - '@pim_extended_attribute_type.localization.presenter.string_collection'
        tags:
            - { name: oro_datagrid.extension.formatter.property, type: product_value_string_collection }
