parameters:
    pim_extended_attribute_type.array_converter.flat_to_standard.range_converter.class: Pim\Bundle\ExtendedAttributeTypeBundle\ArrayConverter\FlatToStandard\Product\ValueConverter\RangeConverter
    pim_extended_attribute_type.array_converter.standard_to_flat.range_converter.class: Pim\Bundle\ExtendedAttributeTypeBundle\ArrayConverter\StandardToFlat\Product\ValueConverter\RangeConverter

    pim_connector.array_converter.flat_to_standard.product.attribute_column_info_extractor.class: Pim\Bundle\ExtendedAttributeTypeBundle\ArrayConverter\FlatToStandard\Product\AttributeColumnInfoExtractor
    pim_connector.array_converter.flat_to_standard.product.attribute_columns_resolver.class: Pim\Bundle\ExtendedAttributeTypeBundle\ArrayConverter\FlatToStandard\Product\AttributeColumnsResolver
    pim_connector.array_converter.flat_to_standard.product.columns_merger.class: Pim\Bundle\ExtendedAttributeTypeBundle\ArrayConverter\FlatToStandard\Product\ColumnsMerger

services:
    pim_extended_attribute_type.array_converter.flat_to_standard.range_converter:
        class: '%pim_extended_attribute_type.array_converter.flat_to_standard.range_converter.class%'
        tags:
            - { name: 'pim_connector.array_converter.flat_to_standard.product.value_converter' }

    pim_extended_attribute_type.array_converter.standard_to_flat.range_converter:
        class: '%pim_extended_attribute_type.array_converter.standard_to_flat.range_converter.class%'
        arguments:
            - '@pim_connector.array_converter.flat_to_standard.product.attribute_columns_resolver'
        tags:
            - { name: 'pim_connector.array_converter.standard_to_flat.product.value_converter' }

    pim_extended_attribute_type.array_converter.standard_to_flat.product.value_converter.text_collection:
        class: '%pim_connector.array_converter.standard_to_flat.product.value_converter.text.class%'
        arguments:
            - '@pim_connector.array_converter.flat_to_standard.product.attribute_columns_resolver'
            - ['pim_extended_attribute_text_collection']
        tags:
            - { name: 'pim_connector.array_converter.standard_to_flat.product.value_converter' }

    pim_extended_attribute_type.array_converter.flat_to_standard.product.value_converter.text_collection:
        class: '%pim_connector.array_converter.flat_to_standard.product.value_converter.text.class%'
        parent: pim_connector.array_converter.flat_to_standard.product.value_converter.abstract
        arguments:
            - ['pim_extended_attribute_text_collection']
        tags:
            - { name: 'pim_connector.array_converter.flat_to_standard.product.value_converter' }

