parameters:
    pim_extended_attribute_type.attribute_icons:
        pim_extended_attribute_type_range: resize-horizontal
        pim_extended_attribute_type_text_collection: book
        pim_extended_attribute_type_url_collection: picture
