parameters:
    pim_extended_attribute_type.provider.field.string_collection.class: Pim\Bundle\ExtendedAttributeTypeBundle\Provider\Field\StringCollectionProvider

services:
    pim_extended_attribute_type.provider.field.string_collection:
        class: '%pim_extended_attribute_type.provider.field.string_collection.class%'
        tags:
            - { name: pim_enrich.provider.field, priority: 100 }
