parameters:
    pim_extended_attribute_type.provider.field.text_collection.class: Pim\Bundle\ExtendedAttributeTypeBundle\Provider\Field\TextCollectionProvider

services:
    pim_extended_attribute_type.provider.field.text_collection:
        class: '%pim_extended_attribute_type.provider.field.text_collection.class%'
        tags:
            - { name: pim_enrich.provider.field, priority: 100 }
