services:
    pim_extended_attribute_type.doctrine.query.filter.range:
        class: '%pim_extended_attribute_type.doctrine.query.filter.range.class%'
        arguments:
            - '@pim_catalog.validator.helper.attribute'
            - ['EMPTY']
        tags:
            - { name: 'pim_catalog.doctrine.query.filter', priority: 30 }

    pim_extended_attribute_type.doctrine.query.filter.text_collection:
        class: '%pim_catalog.doctrine.query.filter.string.class%'
        arguments:
            - '@pim_catalog.validator.helper.attribute'
            - ['pim_catalog_text_collection', 'pim_extended_attribute_type_url_collection']
            - ['CONTAINS', 'DOES NOT CONTAIN', 'EMPTY', 'NOT EMPTY']
        tags:
            - { name: 'pim_catalog.doctrine.query.filter', priority: 30 }
